spring:
  h2:
    console:
      enabled: true
      path: /ecommerce-console
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:mem:ecommerce-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password: password
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        use_sql_comments: true
        format_sql: true